package io.mosip.tuvali.wallet.transfer.message

abstract class IMessage(val msgType: TransferMessageTypes) {
  enum class TransferMessageTypes {
    INIT_RESPONSE_TRANSFER,
    RESPONSE_SIZE_WRITE_PENDING,
    RESPONSE_SIZE_WRITE_SUCCESS,
    RESPONSE_SIZE_WRITE_FAILED,
    INIT_RESPONSE_CHUNK_TRANSFER,
    CHUNK_WRITE_TO_REMOTE_STATUS_UPDATED,
    RESPONSE_CHUNK_WRITE_SUCCESS,
    RESPONSE_CHUNK_WRITE_FAILURE,
    RESPONSE_TRANSFER_COMPLETE,
    RESPONSE_TRANSFER_FAILED,

    READ_TRANSMISSION_REPORT,
    HANDLE_TRANSMISSION_REPORT,

    INIT_RETRY_TRANSFER,
  }
}
