name: Android Artifact Build

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
      publication_type:
        description: 'Select artifact type to publish: aar, jar, or both'
        required: true
        default: both
        type: string
      release_type:
        description: 'Select release type to publish: snapshot or release'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - snapshot
          - release
      group_path:
        description: 'Select Maven group path'
        required: true
        type: choice
        default: io/inji
        options:
          - io/inji
          - io/mosip

jobs:
  publish-snapshot:
    if: ${{ inputs.release_type == 'snapshot' }}
    uses: mosip/kattu/.github/workflows/maven-publish-android.yml@v0.0.1
    with:
      SERVICE_LOCATION: 'kotlin'
      ANDROID_SERVICE_LOCATION: 'android'
      GROUP_PATH: ${{ inputs.group_path }}
      JAVA_VERSION: 17
      LICENSE_NAME: 'Apache 2.0'
      RELEASE_TYPE: ${{ inputs.release_type }}
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{ secrets.GRADLE_OSSRH_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}

  publish-release:
    if: ${{ inputs.release_type == 'release' }}
    uses: mosip/kattu/.github/workflows/maven-publish-android-download.yml@v0.0.1
    with:
      SERVICE_LOCATION: 'kotlin'
      ANDROID_SERVICE_LOCATION: 'android'
      GROUP_PATH: ${{ inputs.group_path }}
      JAVA_VERSION: 17
      LICENSE_NAME: 'Apache 2.0'
      RELEASE_TYPE: ${{ inputs.release_type }}
      PUBLICATION_TYPE: ${{ inputs.publication_type }}
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{ secrets.GRADLE_OSSRH_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
